# Generated by Django 5.2.4 on 2025-09-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_healthtip_dailytip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytip',
            name='date',
            field=models.DateField(),
        ),
    ]
